AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-cloudcustodian

  Sample SAM Template for serverless-cloudcustodian

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
Resources:
  CloudCustodianFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cloud-custodian-lambda
      Role: !GetAtt CloudCustodianFunctionRole.Arn
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
  CloudCustodianFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloud-custodian-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess